#!/bin/bash
# 01-build-prod-image.sh — Real Oracle Linux 9 OS Image Builder
set -euo pipefail
# shellcheck source=scripts/prod-config.sh
source "$(dirname "$0")/prod-config.sh"
check_root

TMP_DIR="$(mktemp -d)"

cleanup() {
    umount "$MOUNT_DIR" 2>/dev/null || true
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

write_package_list() {
    local output_file="$1"
    rpm --root="$MOUNT_DIR" -qa --qf '%{NAME}\n' | sort -u > "$output_file"
}

install_available_base_image_packages() {
    local pkg

    for pkg in "${BASE_IMAGE_PACKAGE_CANDIDATES[@]}"; do
        if dnf -q repoquery --releasever=9 "$pkg" 2>/dev/null | grep -q .; then
            log_info "Installing base image package candidate: $pkg"
            if ! dnf install -y "$pkg" --installroot="$MOUNT_DIR" --releasever=9 --setopt=install_weak_deps=False &>/dev/null; then
                log_warn "  Candidate $pkg was available but could not be installed; continuing."
            fi
        fi
    done
}

log_info "=== Phase 1: Allocating True 10GB Disk Volume ==="
truncate -s 10G "$IMAGE_FILE"
mkfs.ext4 -F -L "OL9_REAL_ROOT" "$IMAGE_FILE" &>/dev/null

log_info "Mounting block storage loop device..."
mount -o loop "$IMAGE_FILE" "$MOUNT_DIR"

log_info "Installing real, functional Core Base OS packages via DNF..."
dnf groupinstall -y "Core" --installroot="$MOUNT_DIR" --releasever=9 --setopt=install_weak_deps=False &>/dev/null

log_info "Installing kernel/base-image candidates when available..."
install_available_base_image_packages

BASE_PACKAGE_LIST="${TMP_DIR}/base-packages.txt"
ALL_PACKAGE_LIST="${TMP_DIR}/all-packages.txt"
PLATFORM_PACKAGE_LIST="${TMP_DIR}/platform-packages.txt"

log_info "Capturing frozen base package baseline from the live RPM database..."
write_package_list "$BASE_PACKAGE_LIST"

log_info "Installing platform packages and tools..."
dnf install -y "${PLATFORM_PACKAGES[@]}" --installroot="$MOUNT_DIR" --releasever=9 --setopt=install_weak_deps=False &>/dev/null

log_info "Capturing platform package delta from the live RPM database..."
write_package_list "$ALL_PACKAGE_LIST"
comm -13 "$BASE_PACKAGE_LIST" "$ALL_PACKAGE_LIST" > "$PLATFORM_PACKAGE_LIST"

log_info "Writing generated engineering manifest inside real image..."
{
    cat <<EOF
# OL9 Live Image Manifest
# Generated by 01-build-prod-image.sh from the image RPM database.
# [base] is the frozen Core/kernel/base-image package baseline.
# [platform] is the package delta introduced by platform packages/tools.
[base]
EOF
    cat "$BASE_PACKAGE_LIST"

    cat <<EOF

[platform]

EOF
    cat "$PLATFORM_PACKAGE_LIST"

    cat <<EOF

[requested-platform]
EOF
    printf '%s\n' "${PLATFORM_PACKAGES[@]}"
} > "${MOUNT_DIR}/${MANIFEST_FILE}"

log_info "Seeding real-world untracked data (dynamic application logs and custom configs)..."
echo "ENV=PRODUCTION_VERIFIED" > "${MOUNT_DIR}/etc/app-runtime.conf"
echo "LOG_LEVEL=DEBUG" > "${MOUNT_DIR}/var/log/app-engine.log"

log_info "Finalizing block storage sync and unmounting clean..."
cleanup
trap - EXIT

log_success "Real 10GB Linux Master Image successfully built at: $IMAGE_FILE"
